let array =  [
    {"adult":false,"backdrop_path":"/393mh1AJ0GYWVD7Hsq5KkFaTAoT.jpg","genre_ids":[12,28,878],"id":507086,"original_language":"en","original_title":"Jurassic World Dominion","overview":"Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.","popularity":14064.562,"poster_path":"/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg","release_date":"2022-06-01","title":"Jurassic World Dominion","video":false,"vote_average":7,"vote_count":1680},{"adult":false,"backdrop_path":"/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg","genre_ids":[10751,16,12,35,14],"id":438148,"original_language":"en","original_title":"Minions: The Rise of Gru","overview":"A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.","popularity":10287.489,"poster_path":"/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg","release_date":"2022-06-29","title":"Minions: The Rise of Gru","video":false,"vote_average":7.6,"vote_count":402},

    {"adult":false,"backdrop_path":"/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg","genre_ids":[28,18],"id":361743,"original_language":"en","original_title":"Top Gun: Maverick","overview":"After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.","popularity":9543.951,"poster_path":"/62HCnUTziyWcpDaBO2i1DX17ljH.jpg","release_date":"2022-05-24","title":"Top Gun: Maverick","video":false,"vote_average":8.4,"vote_count":1600},{"adult":false,"backdrop_path":"/nW5fUbldp1DYf2uQ3zJTUdachOu.jpg","genre_ids":[16,878,12,28,10751],"id":718789,"original_language":"en","original_title":"Lightyear","overview":"Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.","popularity":7159.091,"poster_path":"/4sBbVik86fOuyRY4kFGbn2sooQk.jpg","release_date":"2022-06-15","title":"Lightyear","video":false,"vote_average":7.2,"vote_count":763},{"adult":false,"backdrop_path":"/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg","genre_ids":[27,53],"id":756999,"original_language":"en","original_title":"The Black Phone","overview":"Finney Shaw, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.","popularity":5992.936,"poster_path":"/bxHZpV02OOu9vq3sb3MsOudEnYc.jpg","release_date":"2022-06-22","title":"The Black Phone","video":false,"vote_average":7.8,"vote_count":772},
]
const Tes = ()=>{
    let data= [];
    let data2= 2 + 4 ;
    data= data2;

    return data;
}

console.log(array);